# Generated by Django 4.2.2 on 2023-09-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_advertisement_article_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('logo', models.ImageField(upload_to='company_logo')),
                ('history', models.TextField()),
                ('contacts', models.TextField()),
                ('certificate', models.ImageField(upload_to='certificates')),
            ],
        ),
    ]
